config/routes.rb
Rails.application.routes.draw do

  resources :reports
  root to: "reports#index"

  namespace :api do
    namespace :v1 do
        get '/elections' => 'elections#index'
        post '/elections' => 'elections#create'
      end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :report, optional: true
end

app/models/report.rb
class Report < ApplicationRecord
  validates_presence_of :nombre

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /Categorys
  # GET /Categorys.json
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json { render :json => @categories }
    end
  end

  # GET /Categorys/1
  # GET /Categorys/1.json
  def show
  end

  # GET /Categorys/new
  def new
    @category = Category.new
  end

  # GET /Categorys/1/edit
  def edit
  end

  # POST /Categorys
  # POST /Categorys.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Categorys/1
  # PATCH/PUT /Categorys/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Categorys/1
  # DELETE /Categorys/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categorys_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nombre, :report_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    respond_to do |format|
      format.html
      format.json { render :json => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:nombre, :pdte_mpal, :dip_local, :dip_federal, :renovacion_cdm, :situacion_municipio, :situacion_cdm, :temas_rednion, :image, :observaciones, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.fixed-top.bg-inverse
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{:href => "/"}
    %img.d-inline-block.align-top{:alt => "", :height => "30", :src => "/logopri.svg", :width => "30"}>/
    CDE Hidalgo
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => "/"}
          Municipios
          %span.sr-only (current)
      %li.nav-item.dropdown
        %span.sr-only (current)
        %a#responsiveNavbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => ""} Distritos
        .dropdown-menu{"aria-labelledby" => "responsiveNavbarDropdown"}
          %a.dropdown-item{:href => "/locals"} Locales
          %a.dropdown-item{:href => "/federals"} Federales
      %li.nav-item
        %a.nav-link.disabled{:href => "#"} Disabled
    %ul.nav.navbar-nav.float-lg-right
      %li.nav-item.nav-link.btn
        = link_to "Log out", root_path, method: :delete
      %li.nav-item.nav-link.btn
        = link_to "Sign In", root_path
    %form.form-inline.mt-2.mt-md-0
      %input.form-control.mr-sm-2{:placeholder => "Search", :type => "text"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/elections/new.html.haml
#new-election-form
  {{message}}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Appnotes
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
  %body
    %p.notice= notice
    %p.alert= alert
    = render "nav"
    .container
      = yield
    = javascript_include_tag 'application'

app/views/reports/_form.html.haml
= simple_form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  = f.input :nombre, label: 'Nombre', error: 'Nombre de usuario es obligatorio'
  = f.input :category do
    = f.select :category_id, Category.all.map { |c| [c.nombre, c.id ] }, {}, { class: "form-control input-lg" }
  = f.input :pdte_mpal, label: 'Presidente Municipal'
  = f.input :dip_local, label: 'Diputado Local'
  = f.input :dip_federal, label: 'Diputado Federal'
  = f.input :renovacion_cdm, as: :date, order: [:day, :month, :year]
  = f.input :situacion_municipio, as: :text, label: 'Situación Municipio'
  = f.input :situacion_cdm, as: :text, label: 'Situación CDM'
  = f.input :temas_rednion, as: :text, label: 'Temas Reunión'
  = f.input :image, as: :file
  = f.input :observaciones, as: :text, label: 'Observaciones'
  %br

  #new-election-form
    {{message}}

  %br

  = f.button :submit, "Guardar", class: "btn btn-primary"

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
%h1 Listado Reportes

%table.table.table-hover
  %thead
    %tr
      %th Nombre
      %th Pdte mpal
      %th Dip local
      %th Dip federal

  %tbody
    - @reports.each do |report|
      %tr
        %td
          = link_to report.nombre, report
          %br
          \ Renovacion CDM:
          %br
            = report.renovacion_cdm.strftime("%d-%m-%Y")

        %td= report.pdte_mpal
        %td= report.dip_local
        %td= report.dip_federal
        %td
          = link_to 'Edit', edit_report_path(report)
          = link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Report', new_report_path, class: "btn btn-success"

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice

%h1= @report.nombre
%p
  %b Pdte mpal:
  = @report.pdte_mpal
%p
  %b Dip local:
  = @report.dip_local
%p
  %b Dip federal:
  = @report.dip_federal
%p
  %b Renovacion cdm:
  = @report.renovacion_cdm
%p
  %b Situacion municipio:
  = @report.situacion_municipio
%p
  %b Situacion cdm:
  = @report.situacion_cdm
%p
  %b Temas reunion:
  = @report.temas_rednion
%p
  %b Image:
  = @report.image
%p
  %b Observaciones:
  = @report.observaciones

= link_to 'Edit', edit_report_path(@report), class: "btn btn-success"
\|
= link_to 'Back', reports_path, class: "btn btn-secondary"